server:
  port: 18085
spring:
  application:
    name: search
  #  data:
  #    elasticsearch:
  #      cluster-nodes:
  elasticsearch:
    rest:
      uris: http://47.97.220.212:9200


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#超时配置
ribbon:
  ReadTimeout: 300000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000